CREATE TABLE `aktie_levermann_punkte` (
  `idaktie_levermann_punkte` int(11) NOT NULL AUTO_INCREMENT,
  `id_aktie` int(11) NOT NULL,
  `datum` datetime NOT NULL,
  `ek-rendite` int(11) DEFAULT '0',
  `ebit` int(11) DEFAULT '0',
  `ek-quote` int(11) DEFAULT '0',
  `kgv` int(11) DEFAULT '0',
  `kgv5` int(11) DEFAULT '0',
  `analysten` int(11) DEFAULT '0',
  `reaktion_quartals_zahlen` int(11) DEFAULT '0',
  `gewinnrevision` int(11) DEFAULT '0',
  `kursverlauf6` int(11) DEFAULT '0',
  `kursverlauf12` int(11) DEFAULT '0',
  `momentum` int(11) DEFAULT '0',
  `reversaleffekt` int(11) DEFAULT '0',
  `gewinnwachstum` int(11) DEFAULT '0',
  `gesamtpunkzahl` int(11) DEFAULT NULL,
  PRIMARY KEY (`idaktie_levermann_punkte`),
  KEY `id_aktie_idx` (`id_aktie`),
  CONSTRAINT `id_aktie` FOREIGN KEY (`id_aktie`) REFERENCES `aktien_information` (`aktie_id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `aktie_levermann_values` (
  `idaktie_levermann_values` int(11) NOT NULL AUTO_INCREMENT,
  `id_aktie` int(11) NOT NULL,
  `datum` datetime NOT NULL,
  `kurs` decimal(18,2) DEFAULT NULL,
  `analyst_bewertung` int(11) DEFAULT NULL COMMENT '1: Kaufen 5: Verkaufen',
  `analysten_anzahl` int(11) DEFAULT NULL,
  `kurs_ziel` decimal(18,2) DEFAULT NULL,
  `kgv` decimal(7,2) DEFAULT NULL,
  `kgv_5` decimal(7,2) DEFAULT NULL,
  `quartalszahlen_letzte` datetime DEFAULT NULL,
  `veraenderung_index_quartaltag` decimal(7,2) DEFAULT NULL,
  `veraenderung_kurs_quartaltag` decimal(7,2) DEFAULT NULL,
  `veraenderung_kurs_6m` decimal(7,2) DEFAULT NULL,
  `veraenderung_kurs_12m` decimal(7,2) DEFAULT NULL,
  `gewinn` decimal(7,2) DEFAULT NULL,
  `gewinn_nj` decimal(7,2) DEFAULT NULL,
  `gewinn_veraenderung` decimal(7,2) DEFAULT NULL COMMENT 'Anpassung der Gewinnerwartung zur dem Wert von vor vier Wochen',
  `gewinn_veraenderung_nj` decimal(7,2) DEFAULT NULL COMMENT 'Anpassung der Gewinnerwartung zur dem Wert von vor vier Wochen',
  PRIMARY KEY (`idaktie_levermann_values`),
  KEY `id_aktie_idx` (`id_aktie`),
  CONSTRAINT `id_aktie_information` FOREIGN KEY (`id_aktie`) REFERENCES `aktien_information` (`aktie_id`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=latin1;

CREATE TABLE `aktien_information` (
  `aktie_id` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(90) DEFAULT NULL,
  `ISIN` varchar(12) DEFAULT NULL,
  `notation_id` int(11) DEFAULT NULL,
  `Groeße` varchar(1) DEFAULT NULL COMMENT 'L: Large Cap\nM: Mid Cap\nS: Small Cap',
  `Art` varchar(45) DEFAULT NULL,
  `Benchmark` varchar(15) DEFAULT NULL,
  `Marketscreener-ID` varchar(15) DEFAULT NULL,
  `Onvista-URL` varchar(150) DEFAULT NULL,
  `FinanzenNet-URL` varchar(150) DEFAULT NULL,
  `Marketscreener-URL` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`aktie_id`),
  UNIQUE KEY `idaktien_UNIQUE` (`aktie_id`),
  UNIQUE KEY `ISIN_UNIQUE` (`ISIN`),
  UNIQUE KEY `Symbol_UNIQUE` (`notation_id`),
  UNIQUE KEY `Marketscreener-ID_UNIQUE` (`Marketscreener-ID`),
  KEY `fk_aktien_idx` (`ISIN`,`Onvista-URL`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=latin1 COMMENT='Alle Informationen die sich nicht ändern: Name, ISIN, Symbol, Links, usw.';

CREATE TABLE `aktien_jaehrliche_daten` (
  `idaktien_jaehrliche_daten` int(11) NOT NULL AUTO_INCREMENT,
  `aktie_id` int(11) NOT NULL,
  `Jahr` smallint(4) NOT NULL,
  `return_on_equity` decimal(7,2) DEFAULT NULL,
  `ebit` decimal(7,2) DEFAULT NULL,
  `eigenkapitalquote` decimal(7,2) DEFAULT NULL,
  `kgv` decimal(7,2) DEFAULT NULL,
  `eps` decimal(7,2) DEFAULT NULL,
  `Q1` datetime DEFAULT NULL,
  `Q2` datetime DEFAULT NULL,
  `Q3` datetime DEFAULT NULL,
  `Q4` datetime DEFAULT NULL,
  PRIMARY KEY (`idaktien_jaehrliche_daten`),
  KEY `aktie_id_idx` (`aktie_id`),
  CONSTRAINT `aktie_id` FOREIGN KEY (`aktie_id`) REFERENCES `aktien_information` (`aktie_id`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=112 DEFAULT CHARSET=latin1 COMMENT='Daten die sich nicht mehr ändern';
